### ISSUE TITLE
Conversion to tess3.obj

### ISSUE THREAD

**Issue by nperry44** [bcm-uga/TESS3_encho_sen#11]
Hello,

When I run the command:
tess3.obj <- tess3(X = genotype, coord = coordinates, K = 1:12, method = "projected.ls", ploidy = 2, openMP.core.num = 4)

I get: 
Error in CheckXBinCoord(XProba, coord) : 
  Number of row of coord and X/XBin must be the same

Does anyone know how to fix this? genotype is   tess3.data$X, where tess3.data is read in through read.delim

coordinates is a coordinate file read in through read.delim and created as.matrix with the tess3.data

I am reading in the data from a structure file with 20 individuals and 83653 markers, and there are 20 individuals with 6 extra columns. Thanks!

**Comment by francoio** [comment]
hi,

The issue might come from the structure format of the genotypes. The tess3 program requires a SNP-like format where genotypes are coded  0, 1, 2. 

Suggestion: use the "tess2tess3" function to convert from the structure format to the correct matrix entries. 

best wishes

**Comment by nperry44** [comment]
There was an error in the coordinates file. I had 20 diploid individuals, so I made 2 entries for each in the coordinates file. However, I discovered that there only had to be 1 entry per individual. I got tess3r to work by using this and a structure format where the genotypes were coded as 0,1 and -9.
Thanks again for your help.
