### ISSUE TITLE
Unable to install tess3 in R version 3.6.1

### ISSUE THREAD

**Issue by thomlmarshall** [bcm-uga/TESS3_encho_sen#12]
I am using this command to install tess3 ("devtools::install_github("bcm-uga/TESS3_encho_sen") and am getting the following message:

ERROR: compilation failed for package ‘tess3r’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/tess3r’
Error: Failed to install 'tess3r' from GitHub:
  (converted from warning) installation of package ‘/var/folders/2j/0gg10vvj4sn3sbn1bvq7xcbh0000gn/T//RtmpnOCkU6/file3cf27303530/tess3r_1.1.0.tar.gz’ had non-zero exit status

**Comment by francoio** [comment]
Could you please copy the full text of the message error and say what your os is. Installation failure is often due to missing external libraries in the OS

**Comment by thomlmarshall** [comment]
Here's the full message when I run the installation command. I'm using macOS Mojave.

Downloading GitHub repo bcm-uga/TESS3_encho_sen@master
✔  checking for file ‘/private/var/folders/2j/0gg10vvj4sn3sbn1bvq7xcbh0000gn/T/RtmpebOrVo/remotes10be6921f84/bcm-uga-TESS3_encho_sen-03bd3c9/DESCRIPTION’ ...
─  preparing ‘tess3r’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘tess3r_1.1.0.tar.gz’
   
* installing *source* package ‘tess3r’ ...
** using staged installation
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -fopenmp -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘tess3r’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/tess3r’
Error: Failed to install 'tess3r' from GitHub:
  (converted from warning) installation of package ‘/var/folders/2j/0gg10vvj4sn3sbn1bvq7xcbh0000gn/T//RtmpebOrVo/file10be63e8d687/tess3r_1.1.0.tar.gz’ had non-zero exit status

**Comment by francoio** [comment]
See closed thread #7, and how to install openMP on mac-os. It seems that the link below provides a good answer, but i did not try recently.

https://thecoatlessprofessor.com/programming/cpp/openmp-in-r-on-os-x/
