### ISSUE TITLE
Calibration of tests: pvalue

### ISSUE THREAD

**Issue by ahmaduaf** [bcm-uga/TESS3_encho_sen#15]
Hello,
I am using Tess3r for genome scan on radseq data of a tetraploid species (this is the only tool I am aware of which accepts polyploid data and can perform genome scan). I have 16000 SNPs from 126 individuals. After selecting "optimal-K" I plotted p-values, however, the resulted plot shows lot of noise, see attached pictures for K= 3 and K =5, I was wondering if there is a way to improve the calibration of tests so that background noise can be reduced. I looked into the manual but it does not provide much detail. My input data is highly filtered and there is no missing data. All SNPs are present across all individuals.
Thank you
![image](https://user-images.githubusercontent.com/36341101/80207294-3429e580-862e-11ea-80d2-05ddde3f0a7a.png)

![image](https://user-images.githubusercontent.com/36341101/80207365-4ad03c80-862e-11ea-9158-c69b77c5699a.png)

**Comment by francoio** [comment]
hi, 

no test calibration method would remove the noise in the data. Noise impacts the power of (all) genome scan methods.

Assuming K = 5 is the "optimal" K, the histogram has a good shape. This means that  standard multiple testing corrections could be applied to this set of p-values. 

Note that Fst-like genome scans for selection are also available in the R package LEA. They are performed with snmf which allows polyploids. Perhaps you could check them for comparison. The reference paper is Martins et al. Molecular Ecology 2016.

**Comment by ahmaduaf** [comment]
hi,
thank you for the input.

**Comment by ahmaduaf** [comment]
Hello, Sorry to write again,
Sorry maybe its a very basic question regarding the tess3r, how one can determine the expected level of FDR, I have seen in 2 different tutorials using two different thresholds. Also in original articles ( https://doi.org/10.1111/mec.13513; https://doi.org/10.1111/1755-0998.12471) different thresholds have been used sometime really stringent (expected FDR value of 10-30) other time fairly relaxing (expected FDR level of 7%). I wanted to ask is there a systematic way to set an expected FDR level or its a subjective decision.
Thank you

**Comment by francoio** [comment]
Be aware that FDR is not type I error. So 5% doesn't mean the same thing for FDR and for classical significance thresholds (for p-values). FDR describes the number of false positives in the proposed list of candidates. If the list is short (like a dozen of genes), then it could be reasonable to increase the FDR.
