### ISSUE TITLE
SNP data format

### ISSUE THREAD

**Issue by SamWittwer** [bcm-uga/TESS3_encho_sen#17]
Hello

Apologies for using the github issues to ask a rather basic question:

I have a dataset with 112 diploid individuals and 21179 biallelic SNPs. I've parsed a vcf file into a 112x21182 dataframe to conform with the format of the example datasets with col 1 = popid, cols 2+3 coordinates X/Y, cols 4:n genotype for each marker encoded as 0 (hom REF),1,2 (hom ALT). 

I am now uncertain as to how I can correctly import this with tess2tess3. When I specify diploid = TRUE I am getting an error as it probably expects either two rows or two columns per marker.  When i specify as haploid it works but I'm not sure if this is appropriate when I have a diploid organism? Or is this merely a technicality when converting?

Thank you very much and best wishes

Samuel Wittwer

**Comment by francoio** [comment]
hi samuel, 

You completed the job by parsing the vcf file, and for your data, tess2tess3 is useless. Just use read.table or data.table::fread to import your data in R, then create separate matrix objects for the coordinates (col 2:3) and genotypes (col 4:n). Just be aware that the missing values must be encoded as NA. tess3 will run with these two matrices. 

Send me emails if some problem remains. 

best wishes
olivier
