### ISSUE TITLE
tess2tess3 structure file - Error in as.matrix(coord)

### ISSUE THREAD

**Issue by btmartin721** [bcm-uga/TESS3_encho_sen#18]
Hello,

I am trying to convert a structure file to tess3 format. My structure file has four extra columns: 

1. individual IDs
2. population IDs
3. Longitude
4. Latitude

Then the genotypes (two rows per individual).

When I try to run tess2tess3, it gives the error:

```Error in as.matrix(coord) : object 'coord' not found```  

Am I doing something wrong with the lon/lat coordinates? I have them as columns 3 and 4 in the data.frame. The documentation seems like it wants them set as as extra columns in the structure file. I looked at the R code for tess2tess3, and if (TESS == FALSE) coords never gets set. It only gets set if TESS == TRUE.

Thanks.

-Bradley

**Comment by btmartin721** [comment]
I Bandaid fixed it by passing the function my own coord data.frame.

**Comment by francoio** [comment]
hi Bradley, 

your structure file is also tess file. So, set TESS = TRUE in tess2tess3 (the default setting) and tell the command that there are two extra columns. IDs are not used. 

This should be fast, so could could check that your own format was correct. 

Olivier

**Comment by btmartin721** [comment]
Ok I see. It was just confusing because the documentation says to set TESS = FALSE if it's a structure file.
