### ISSUE TITLE
struct2geno issue

### ISSUE THREAD

**Issue by joqb** [bcm-uga/TESS3_encho_sen#22]
Hello,
I'm aware that this is more of a LEA issue, but you refer to the functions from LEA to convert data.

So here is the problem:
I have a dataset with 150 diploid individuals and 10 markers in a STRUCTURE file format. It seems that it reads  everything well but then find errors.

> struct2geno(input.file="7pops_neu_no_extra.str", ploidy=2, FORMAT=1)
Input file in the STRUCTURE format. The genotypic matrix has 150 individuals and 20 markers. 
The number of extra rows is 0 and the number of extra columns is 0 .
Missing alleles are encoded as -9 , converted as 9.
Fehler in struct2geno(input.file = "7pops_neu_no_extra.str", ploidy = 2,  : 
  No polymorphism detected at locus 9 
 Check and rerun.No polymorphism detected at locus 41 
 Check and rerun.No polymorphism detected at locus 49 
 Check and rerun.No polymorphism detected at locus 55 
 Check and rerun.No polymorphism detected at locus 62 
 Check and rerun.

What is also surprising is that it mentions locus 41, 49, 55, and 62 but I have only 10 loci. And Locus 9 is not even monomorphic....

Any idea?

Best regards,
Jonathan

**Comment by francoio** [comment]
hi, 

Locus here is a generic term (perhaps from LEA). If you have multi-allelic markers, then each allele at each marker is considered a "locus". This is also how STRUCTURE's admixture works. 

Thus term "locus" and the numbers 41, 49, 55 refer to alleles detected during the conversion. The total number of alleles (loci) will be larger than the number of markers (10). 

The error message suggests that some markers have monomorphic alleles (check the data or send me copy of those data for checking them)

best 
olivier

**Comment by joqb** [comment]
[7pops_neu.zip](https://github.com/bcm-uga/TESS3_encho_sen/files/7155151/7pops_neu.zip)
Hi Olivier, 

Thanks for the quick reply and your explanations. It is indeed a multi-allelic file (microsatellite loci). I attached my file, so you can check if something is wrong.

Best,
Jonathan

**Comment by francoio** [comment]
Monomorphic alleles are now automatically removed in LEA 3.5.5 function struct2geno(). The message was more a warning message than an error message. The tess3r::tess2tess3 function doesn't produces this error/warning message.
