### ISSUE TITLE
Error in CheckCoord(coord) : Elements of Coord must be of type double

### ISSUE THREAD

**Issue by JimStarrett** [bcm-uga/TESS3_encho_sen#24]
Sorry, I think this has been addressed before ("The coordinates must also be loaded in R, in the (Lon, Lat) format. Use read.table. Again convert them by using "as.matrix"."), but I can't seem to figure out this type double issue. I tried to get around it using as.numerical, unlist, etc., but those created other issues. Any suggestions would be appreciated.

coordinates <- read.table("promy_longlat.coord")
> coordinates
              V1       V2
1    -121.81573, 37.39347
2    -121.69006, 37.57223
3    -121.72083, 37.01167
4    -121.37032, 37.41993
5    -123.55770, 38.92990

> obj <- tess3(X = as.matrix(genotype), coord = as.matrix(coordinates), K = 5,
+              ploidy = 2, method = "projected.ls", openMP.core.num = 1)
Error in CheckCoord(coord) : Elements of Coord must be of type double

**Comment by francoio** [comment]
hi, 
There might be errors (characters) in the "promy_longlat.coord" that read.table converts as factors and then as lead to numerical values. The comma after -121.81573(,) also looks unusal to me. 

best wishes
olivier

**Comment by francoio** [comment]
too fast: read.table converts as factors and then as.matrix leads to incorrect numerical values
