### ISSUE TITLE
Cannot Install on M1 Mac ("CoreFoundation" error)

### ISSUE THREAD

**Issue by georgeomics** [bcm-uga/TESS3_encho_sen#27]
Hello,

I'm using an M1 mac and attempting to install the package `TESS3_encho_sen` into R from github using the command `devtools::install_github("bcm-uga/TESS3_encho_sen")`

Upon doing so I receive the following error: 
```
Error: Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
```

Calling `pkgbuild::check_build_tools(debug = TRUE)`  gives the following multiple times:
```
In file included from solver.cpp:2:
In file included from /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppEigen/include/RcppEigen.h:25:
In file included from /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppEigen/include/RcppEigenForward.h:40:
In file included from /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/SparseExtra:51:
/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppEigen/include/unsupported/Eigen/../../Eigen/src/Core/util/ReenableStupidWarnings.h:14:30: warning: pragma diagnostic pop could not pop, no matching push [-Wunknown-pragmas]
    #pragma clang diagnostic pop
                             ^
19 warnings generated.
/usr/local/clang4/bin/clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib -L/usr/local/clang4/lib -o tess3r.so RcppExports.o error.o genotypeDataFuntions.o graph.o samplerHelpers.o selectionScan.o solver.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation

ld: framework not found CoreFoundation
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [tess3r.so] Error 1
ERROR: compilation failed for package ‘tess3r’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/tess3r’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/ht/18j6z2tj0fs5mjcv462c3yyw0000gn/T//Rtmp0VZ8ex/file133276a16fede/tess3r_1.1.0.tar.gz’ had non-zero exit status
```

Which makes me suspicious it may be ARM64 path issues and the location of "CoreFoundation".

Calling `devtools::load_all()` also generated the following: 
```
Error in `value[[3L]]()`:
! Could not find a root 'DESCRIPTION' file that starts with '^Package' in
  ~/path/to/file.
Are you in your project directory and does your project have a 'DESCRIPTION' file?
```

Any help with this issue is appreciated!

**Comment by francoio** [comment]
yes, it gas a DESCRIPTION file. 

Using  gfortran-12.0.1-20220312-is-darwin20-arm64z for R 4.2.2 and following instructions https://mac.r-project.org/tools/  for Apple M1 worked fine for me. 

Also update Xcode and upgrade ‘RcppEigen’ to the latest release. 

googling "ld: framework not found CoreFoundation" offers additional clues.

**Comment by georgeomics** [comment]
After updating my packages/software and editing my ```R./Makevars``` file (as suggested [HERE](https://stackoverflow.com/questions/58313047/cannot-compile-r-packages-with-c-code-after-updating-to-macos-catalina) and [HERE](https://stackoverflow.com/questions/74534902/resolve-issues-installing-r-packages-after-switch-from-intel-to-apple-silicon), my original error message (and pop up message of needing to install build tools) has gone away and ```bcm-uga/TESS3_encho_sen``` was installed (though with several warnings).

Below is my current ```Makevars``` for reference:
```
# clang: start
CFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
CCFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
CXXFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
# clang: end
```

**Comment by francoio** [comment]
this was useful, thanks.
