### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by joqb** [bcm-uga/TESS3_encho_sen#28]
Hello, 
I have data from a GBS analysis. The genotypic data contains a fair amount of missing data.
By default, missing data are coded as 9 in the geno file, but this seems to interfere with the ploidy check. 
Is it possible to analyze gappy data? And if so, how should the missing data be coded ?

Best,
Jonathan

**Comment by francoio** [comment]
hi, 

tess3r handles objects of type "matrix" and missing data must be encoded as NA. If the genotype matrix is stored in an n times L matrix (n individuals in rows, L loci in columns)  with "9" for missing values, then load it in R and replace the missing values by NA as follows

geno = data.table::fread("example_geno.lfmm")
geno = as.matrix(genotype)
mean(geno == 9) # % of missing values
geno[geno == 9] = NA

then use "geno" in the function tess3(X = geno, ...)

olivier
