### ISSUE TITLE
`map.polygon` is not used for rendering the map

### ISSUE THREAD

**Issue by ekirving** [bcm-uga/TESS3_encho_sen#4]
Great work on the TESS3 package, it makes some really nice figures!

However, there is an issue with `plot.tess3Q()` when using the `map.polygon` parameter. Looking at the code it seems that `map.polygon` (and `raster.filename`) is only used for masking the interpolation surface (i.e. `interpol.stack` in `Crop()`) and is ignored when actually rendering the map. As the rendered map defaults to a low resolution raster (`maps::map()`), this causes ugly pixilation around country borders when using a high resolution `map.polygon`.

I would suggest that two changes are necessary:
1. If either `map.polygon` or `raster.filename` are set, then they should be used for also rendering the map itself.
2. Expose the boolean `map` parameter in both `PlotInterpotationMax()` and `PlotInterpotationAll()` to the public function `plot.tess3Q()`, so that users can optionally choose to suppress rendering of the map itself and just render the masked interpolation surface. In my particular usecase I would like to use different maps for masking and rendering.

**Comment by cayek** [comment]
Hi ekirving,

Thank you for your suggestions, we will take them into account soon.
